name: Build and Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose --color"
          jupyter: true

  unit_tests:
    # [macos-latest, macos-latest, windows-latest]
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      # You can use PyPy versions in python-version.
      # For example, pypy2 and pypy3
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      # You can test your matrix by printing the current Python version
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -U setuptools
          pip install -r requirements.txt
          python -m pip install -U --editable ".[dev]"
      - name: Test with pytest
        run: python -m pytest tests/
